[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["ssl://localhost:8883"]
  topics = ["telemetry/+"]

  username = "nodemcu"
  password = "IOT@Aspire"
  tls_ca = "/etc/telegraf/server-ecc.crt"
  insecure_skip_verify = true

  data_format = "json"
  topic_tag = "topic"

[[processors.regex]]
  [[processors.regex.tags]]
    key = "topic"
    pattern = "^telemetry/(.*)$"
    replacement = "${1}"

[[outputs.influxdb]]
  urls = ["http://localhost:8428"]
